
package hospital.opd.java;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.lang.String;


public class Main extends javax.swing.JFrame {

    private void userlogin() {
        
         
          
          
          
        
    }
  
   public void filereader() throws IOException{ 
        String[] tokens;
        String str;
        
        
        boolean status =false;
        JFrame f;  
        
        
        
        // check if File exists or not 
         
        BufferedReader log;
        log = new BufferedReader(new FileReader("db\\login.txt"));
        String user = getUserName();
        String password =getPassword();
        String usertype = getusertype();
            
        
            
        //System.out.println(log.readLine());
        //System.out.println(log.readLine());
        while ((str = log.readLine()) != null) {
            
            
         
        //System.out.println(user+password);
  // read from FileReader till the end of file 
        tokens = str.split(",");
        //System.out.println(user +" "+ password+"||"+ tokens[0] +" "+ tokens[1] );
        
        
        
            try {
                if ((user.equals(tokens[0])) && (password.equals(tokens[1]))){
                 
                  
                    
                    System.out.println("Logged!");
                    status = true;
                    
                    //for hide current login window and move to main dashboard
                    Hidelogin();
                    Showdashboard();
                    
                    //log.close();
                    break;  //To stop the loop 
                
          
        }
                
            } catch (Exception e) {
                
            }
        
        
        }
        
       
        if (!status){ 
         f=new JFrame(); 
         JOptionPane.showMessageDialog(f,"Incorrect Username and Password.","Try Again",JOptionPane.WARNING_MESSAGE);   
         System.out.println("Not Logged!");
         
       
         //Reset the input boxes
         jTextField2.setText("");
         jPasswordField1.setText("");
         
         
         log.close();
        }  
   
         
      
      
        
        
// close the file 
          
       }
   public void Showdashboard(){
        Dashboard d = new Dashboard();
        d.setVisible(true);
   }
   public void Hidelogin(){
       setVisible(false);
   }

    
    public String getUserName(){
       String user = jTextField2.getText();
       return user;
       
   }
   public String getPassword(){
       String password = jPasswordField1.getText();
       return password;
   }
   public String getusertype(){
   String usertype = jComboBox1.getSelectedItem().toString();
   return usertype;
   }
    
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sahan Sandeepa\\Desktop\\project Java\\firstpage.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sahan Sandeepa\\Desktop\\project Java\\firstpage.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 700));

        setSize(new java.awt.Dimension(887, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
